version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

  zipkin:
    image: openzipkin/zipkin:2.24
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  service-reg:
    image: kdixit05/servicereg:latest
    container_name: service-reg
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker

  configserver:
    image: kdixit05/configserver:latest
    container_name: configserver
    ports:
      - "8080:8080"
    depends_on:
      - service-reg
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-reg:8761/eureka/

  gateway:
      image: kdixit05/gateway:latest
      container_name: gateway
      restart: unless-stopped
      ports:
        - "8085:8085"
      depends_on:
        - configserver
        - service-reg
      environment:
        SPRING_PROFILES_ACTIVE: docker
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-reg:8761/eureka/
        SPRING_ZIPKIN_BASEURL: http://zipkin:9411

  companyms:
    image: kdixit05/companyms:latest
    container_name: company
    ports:
      - "8083:8083"
    depends_on:
      - configserver
      - postgres
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-reg:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/companydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_RABBITMQ_HOST: rabbitmq

  jobms:
    image: kdixit05/jobms:latest
    container_name: job
    ports:
      - "8082:8082"
    depends_on:
      - configserver
      - postgres
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-reg:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_RABBITMQ_HOST: rabbitmq

  reviewms:
    image: kdixit05/reviewms:latest
    container_name: review
    ports:
      - "8084:8084"
    depends_on:
      - configserver
      - postgres
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-reg:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reviewdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_RABBITMQ_HOST: rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: