#job-service.url=http://localhost:8082
#company-service.url=http://localhost:8083
#review-service.url=http://localhost:8084
job-service.url=http://job:8082
company-service.url=http://company:8083
review-service.url=http://review:8084

spring.application.name=Job-Service
server.port=8082

spring.datasource.url=jdbc:postgresql://postgres:5432/job
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Etc/UTC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Eureka
eureka.client.serviceUrl.defaultZone=http://service-reg:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.enabled=true
eureka.instance.prefer-ip-address=true
#eureka.instance.ip-address=127.0.0.1

#Zipkin
management.tracing.sampling.probability=1.0

#Config Server
spring.config.import=optional:configserver:http://configserver:8080/


# RESILIENCE4J CIRCUIT BREAKER
resilience4j.circuitbreaker.instances.companyBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.companyBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.companyBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.companyBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.companyBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.companyBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.companyBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.companyBreaker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.companyBreaker.sliding-window-type=count_based
#for retry functionality
resilience4j.circuitbreaker.instances.companyBreaker.max-attempts=5
resilience4j.circuitbreaker.instances.companyBreaker.wait-duration=2s
#for rate limiters
resilience4j.ratelimiter.instances.companyBreaker.limitForPeriod=4
resilience4j.ratelimiter.instances.companyBreaker.limitRefreshPeriod= 4
resilience4j.ratelimiter.instances.companyBreaker.timeout-duration=0

# ACTUATOR
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true




